version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - node_modules_volume:/app/node_modules
    ports:
      - 3000:3000
    tty: true
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    tty: true
    environment:
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_DATABASE=db_name
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - 3306:3306
volumes:
  node_modules_volume: